spring.application.name=djf

spring.datasource.url=jdbc:mysql://mysql:3306/myappdb

spring.datasource.username=appuser
spring.datasource.password=apppassword

pring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL générées par Hibernate (utile pour le débogage)
spring.jpa.show-sql=true
