server {
    listen 80;

    # 1. Servir le Frontend React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        # IMPORTANT pour React Router :
        # Si on demande une page qui n'existe pas physiquement (ex: /users),
        # on renvoie index.html et React gère l'affichage.
        try_files $uri $uri/ /index.html;
    }

    # 2. Rediriger les requêtes API vers Spring Boot (Reverse Proxy)
    location /api {
        # 'app' est le nom du service dans docker-compose
        # Le port 8080 est le port INTERNE de Spring
        proxy_pass http://app:8080;

        # On passe les headers nécessaires
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}